In [8]:

import pandas as pd

In [9]:
df_gols = pd.read_csv('campeonato-brasileiro-gols.csv')

In [10]:
df_gols = pd.DataFrame(df_gols)

In [11]:
df_gols

,partida_id,rodada,clube,atleta,minuto,tipo_de_gol
0,4612,1,Bahia,Anderson Talisca,80,Penalty
1,4615,1,Santos,Gabriel Barbosa,80,NaN
2,4616,1,Palmeiras,Leandro,83,NaN
3,4616,1,Palmeiras,Alan Kardec,88,NaN
4,4619,2,Botafogo-RJ,Pablo Zeballos,75,NaN
...,...,...,...,...,...,...
2195,8400,38,Cruzeiro,Nikão,80,NaN
2196,8401,38,Bahia,Ademir,92,NaN
2197,8402,38,Cuiaba,Clayson,96,NaN
2198,8403,38,Fortaleza,Juan Martín Lucero,96,NaN
2199,8405,38,Vasco,Sergio Antonio De Luiz Junior,82,NaN

In [12]:
df_gols.columns

Index(['partida_id', 'rodada', 'clube', 'atleta', 'minuto', 'tipo_de_gol'], dtype='object')

In [13]:
a74 = df_gols.drop_duplicates('partida_id', keep='first')

In [14]:
a74

,partida_id,rodada,clube,atleta,minuto,tipo_de_gol
0,4612,1,Bahia,Anderson Talisca,80,Penalty
1,4615,1,Santos,Gabriel Barbosa,80,NaN
2,4616,1,Palmeiras,Leandro,83,NaN
4,4619,2,Botafogo-RJ,Pablo Zeballos,75,NaN
5,4620,2,Athletico-PR,Mosquito,78,NaN
...,...,...,...,...,...,...
2195,8400,38,Cruzeiro,Nikão,80,NaN
2196,8401,38,Bahia,Ademir,92,NaN
2197,8402,38,Cuiaba,Clayson,96,NaN
2198,8403,38,Fortaleza,Juan Martín Lucero,96,NaN
2199,8405,38,Vasco,Sergio Antonio De Luiz Junior,82,NaN

In [15]:
a74.to_csv('campeonato-brasileiro-gols-74.csv', index=False)

In [ ]:
#a74.sort_values(by='minuto', ascending=False, inplace=True)

In [16]:
a74['minuto'].sort_values(ascending=True)

11       75
1460     75
1467     75
89       75
766      75
       ...
1332    101
574     101
1805    101
963     102
1867    103
Name: minuto, Length: 1735, dtype: int64

In [ ]:
a74['minuto'].plot(kind='bar')